### ISSUE TITLE
Averaging Spectra Issue

### ISSUE THREAD

**Issue by bdleedahl** [Beamlines-CanadianLightSource/SGM_Nexpy#4] opened 2017-02-01 18:41 UTC
![nexpy_averaging](https://cloud.githubusercontent.com/assets/25489082/22520812/686f0d42-e87b-11e6-8fe0-fed3538062ab.JPG)

In the attached screenshot, you can see three TEY plots. 

From left to right:
1) just my scan No.2 
2) just my scan No.3 
3) averaged scan 2 & 3

Clearly, the averaging isn't happening properly.

**Comment by Henry0422** [comment] 2017-02-01 18:57
I realized the value of TEY between Scan No.2 and No.3 has huge difference. For Scan No.2, the range is 140000-210000. But Scan No.3 has TEY range: 70000-100000.

**Comment by bdleedahl** [comment] 2017-02-01 19:21
I'm not sure why that would matter, the averaged spectrum should look about the same as the original two, since they are nearly identical themselves.

**Comment by regiert** [comment] 2017-02-01 20:41
I'm pretty sure the problem is related to having two scans with very
different count rates.  When the interpolation occurs, some of the data
points have an extra data point from the scan with a high count rate, some
have an extra point from the scan with a lower count rate and the rest have
an equal number of points from each scan.  This is to be expected because
of the semi-random spacing of the data points in each scan.  When we divide
by the number of data points that are added to each bin we are not taking
into account the possibility that the difference in count rates is greater
than just a statistical amount.

We definitely need to address this problem right away because this will be
building noise into all averaged scans (unless they are made with the same
count rates within the statistical deviation).  A lot of people will be
averaging scans that have different count rates - even if they only differ
by a small amount, the effect will be small but it will still be there.

I think we can address this issue by normalizing the binned data
differently.  We need to normalize by a number that is weighted by the
total number of counts in each of the points in the bin rather than just
the number of points placed in the bin.

Tom Regier, PhD.
Beamline Scientist, SGM Beamline
Canadian Light Source, Inc.
tom.regier@lightsource.ca
(306) 657 - 3733

**Comment by JamesJDynes** [comment] 2017-02-02 13:45
Hi All,

I did some  testing of the python program for averaging of spectra in nexpy.   There is definitely noise introduced in the TEY spectra when just adding two spectra together, and when you remove some scans and take the average the result  is not the same as the spectra added together.

For the SDD, taking the average with nexpy is the same as taking the average with axis2000.   However, if you remove scans and take the average get poorer  S/N and there is a shift of the spectra upwards.

Jay

**Comment by Henry0422** [comment] 2017-03-12 23:04
It was fixed and merged into `master` on Feb 21, 2017, with an update of average calculation function. For more details, please check pull request #5 (Weighted Average & Update ytick labels of Summary Plot)

**Closed as completed by Henry0422** 2017-03-12 23:04 UTC
Labels: bug, enhancement
